(() => {
  'use strict';
  const Protocol = Object.freeze({version:1, release:'0.5.0'});
  const JobState = Object.freeze({QUEUED:'queued',ANALYZING:'analyzing',DOWNLOADING:'downloading',PROCESSING:'processing',COMPLETED:'completed',FAILED:'failed',CANCELLED:'cancelled',INTERRUPTED:'interrupted'});
  const DownloadStrategy = Object.freeze({DIRECT_HTTP:'direct_http',YT_DLP:'yt_dlp',FFMPEG:'ffmpeg'});
  const NativeCommand = Object.freeze({PING:'ping',GET_SETTINGS:'get_settings',SAVE_SETTINGS:'save_settings',CHECK_TOOLS:'check_tools',PICK_FILE:'pick_file',PICK_OUTPUT_FOLDER:'pick_output_folder',OPEN_PATH:'open_path',FETCH_INFO:'fetch_info',CONVERT_MP3:'convert_mp3',DOWNLOAD_VIDEO:'download_video',DOWNLOAD_AUDIO:'download_audio',DOWNLOAD_THUMBNAIL:'download_thumbnail',DOWNLOAD_SUBTITLES:'download_subtitles',DOWNLOAD_STREAM:'download_stream',EXTRACT_DETECTED_AUDIO:'extract_detected_audio',DOWNLOAD_DETECTED:'download_detected',CANCEL_JOB:'cancel_job',CHECK_UPDATE:'check_update',APPLY_UPDATE:'apply_update'});
  const NativeEvent = Object.freeze({PONG:'pong',SETTINGS:'settings',SETTINGS_SAVED:'settings_saved',TOOLS_STATUS:'tools_status',FILE_CANCELLED:'file_cancelled',FILE_SELECTED:'file_selected',FOLDER_CANCELLED:'folder_cancelled',FOLDER_SELECTED:'folder_selected',PATH_OPENED:'path_opened',MEDIA_INFO:'media_info',QUEUED:'queued',STARTED:'job_started',PROGRESS:'progress',COMPLETE:'complete',ERROR:'error',CANCELLED:'cancelled',CANCEL_REQUESTED:'cancel_requested',UPDATE_STATUS:'update_status',UPDATE_ERROR:'update_error',UPDATE_PROGRESS:'update_progress',UPDATE_RESTARTING:'update_restarting'});
  const ErrorCode = Object.freeze({INVALID_REQUEST:'invalid_request',UNSUPPORTED:'unsupported',AUTHENTICATION_REQUIRED:'authentication_required',UNAVAILABLE:'unavailable',DRM_PROTECTED:'drm_protected',EXPIRED_URL:'expired_url',HTTP_403:'http_403',EXTRACTION_FAILED:'extraction_failed',CANCELLED:'cancelled',TOOL_MISSING:'tool_missing',IO_ERROR:'io_error',UPDATE_FAILED:'update_failed',INTERNAL:'internal'});
  const Capability = Object.freeze({DIRECT_HTTP:'directHttp',YT_DLP:'ytDlp',FFMPEG:'ffmpeg',FFPROBE:'ffprobe',DENO:'deno',PLAYLISTS:'playlists',SUBTITLES:'subtitles',THUMBNAILS:'thumbnails',BROWSER_SESSION:'browserSession',CANCEL:'cancel',RETRY:'retry',RESTART_RECOVERY:'restartRecovery'});
  const eventState = Object.freeze({queued:JobState.QUEUED,job_started:JobState.ANALYZING,progress:JobState.DOWNLOADING,complete:JobState.COMPLETED,error:JobState.FAILED,cancelled:JobState.CANCELLED});

  function mediaItem(value={}) { return {...value,id:String(value.id||value.url||''),url:String(value.url||''),pageUrl:String(value.pageUrl||''),kind:String(value.kind||'unknown'),container:String(value.container||value.ext||''),contentType:String(value.contentType||''),source:String(value.source||'unknown'),width:Number(value.width)||0,height:Number(value.height)||0,bitrate:Number(value.bitrate)||0,sizeBytes:Number(value.sizeBytes||value.size)||0,sizeExact:!!value.sizeExact,directSafe:!!value.directSafe,protected:!!value.protected}; }
  function downloadRequest(value={}) { return {...value,protocolVersion:Protocol.version,action:String(value.action||''),jobId:String(value.jobId||''),url:String(value.url||''),operation:String(value.operation||value.action||''),strategy:value.strategy||''}; }
  function job(value={}) { const event=value.event||'',state=value.state||eventState[event]||JobState.QUEUED; return {...value,id:String(value.id||value.jobId||''),jobId:String(value.jobId||value.id||''),state,progress:Math.max(0,Math.min(state===JobState.COMPLETED?100:99.5,Number(value.progress)||0))}; }
  function progressEvent(value={}) { const state=value.state||eventState[value.event]||JobState.DOWNLOADING; return {...value,protocolVersion:Number(value.protocolVersion)||Protocol.version,event:value.event||NativeEvent.PROGRESS,state,progress:Math.max(0,Math.min(state===JobState.COMPLETED?100:99.5,Number(value.progress)||0))}; }
  function downloadResult(value={}) { return {...value,jobId:String(value.jobId||''),state:value.state||JobState.COMPLETED,path:String(value.path||''),strategy:value.strategy||''}; }
  function nativeRequest(value={}) { return downloadRequest(value); }
  const api=Object.freeze({Protocol,JobState,DownloadStrategy,NativeCommand,NativeEvent,ErrorCode,Capability,mediaItem,downloadRequest,job,progressEvent,downloadResult,nativeRequest});
  globalThis.LocalToolboxContracts=api;
  if (typeof module !== 'undefined' && module.exports) module.exports=api;
})();
